# Generated by Django 4.2.28 on 2026-02-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('1', 'Hardware'), ('2', 'Software'), ('3', 'Redes'), ('4', 'Otro')], default='1', max_length=30),
        ),
    ]
